var res_name = {
    mainscreen_bg : "mainscreen_bg.png",
    texbox_login : "texbox_login.png",
    btn_dn : "btn_dn.png",
    btn_dn_press : "btn_dn_press.png",
    btn_dk : "btn_dk.png",
    btn_dk_press : "btn_dk_press.png",
//    CB:"CB.png",
 //   chan_1_re:"chan_1_re.png",
 //   chan_2_re:"chan_2_re.png",
//    chan_3_re:"chan_3_re.png",
//    chan_4_re:"chan_4_re.png",
//    chan_5_re:"chan_5_re.png",
//    chan_chia:"chan_chia.png",
//    CHAN_Cards:"bo_chan.png",
//    uMaskCard:"uMaskCard.png" ,
   // vv window
//    vv_window_header: "vv_window_header.png",
//    vv_window_body_bg_1: "vv_window_body_bg_1.png",
//    vv_window_body_content: "vv_window_body_content.png",
//    vv_btn_close: "vv_btn_close.png",
//    vv_btn_close_hover: "vv_btn_close_press.png",
    // vv tab window
//    vv_btn_deselected: "btn_deselected.png",
//    vv_btn_deselected_hover: "btn_deselected_hover.png",
//    vv_btn_selected: "btn_selected.png",
//    vv_btn_selected_hover: "btn_selected_hover.png",	
    
    
    GAME_FONT:"Roboto",
    GAME_FONT_BOLD:"RobotoM",
    TOAST_FONT:"Roboto",

    // chan van van

    vv_btn_big_normal : "btn_tieptuc.png",
    vv_btn_big_press : "btn_tieptuc_press.png",
    vv_btn_big_hover : "btn_tieptuc_hover.png",

    icon_hover_text:"icon_hover_text.png",
    black_1:"black_1.png",
    black_2:"black_2.png",
    trans_1:"trans_1.png",
    trans_2:"trans_2.png",
    btn_an:"btn_an.png",
    btn_an_disable:"btn_an_disable.png",
    btn_an_hover:"btn_an_hover.png",
    btn_an_press:"btn_an_press.png",
    btn_boc:"btn_boc.png",
    btn_boc_disable:"btn_boc_disable.png",
    btn_boc_hover:"btn_boc_hover.png",
    btn_boc_press:"btn_boc_press.png",
    btn_danh:"btn_danh.png",
    btn_danh_disable:"btn_danh_disable.png",
    btn_danh_hover:"btn_danh_hover.png",
    btn_danh_press:"btn_danh_press.png",
    btn_boc_center:"btn_boc_center.png",
    btn_boc_center_disable:"btn_boc_center_disable.png",
    btn_boc_center_hover:"btn_boc_center_hover.png",
    btn_boc_center_press:"btn_boc_center_press.png",
    dia_noc_2:"dia_noc_2.png",
    img0:"0.png",
    img0_OVER:"0_OVER.png",
    img1:"1.png",
    img1_OVER:"1_OVER.png",
    img2:"2.png",
    img2_OVER:"2_OVER.png",
    img3:"3.png",
    img3_OVER:"3_OVER.png",
    img4:"4.png",
    img4_OVER:"4_OVER.png",
    img5:"5.png",
    img5_OVER:"5_OVER.png",
    cuoc_u_hover_5:"cuoc_u_hover_5.png",
    cuoc_u_hover_6:"cuoc_u_hover_6.png",
    cuoc_u_hover_bt:"cuoc_u_hover_bt.png",
    cuoc_u_hover_bt_2:"cuoc_u_hover_bt_2.png",
    vv_select:"select.png",
    cuocho_bg:"cuocho_bg.png",
    imgcheck:"check.png",
    danhsachcuocu_body:"danhsachcuocu_body.png",
    danhsachcuocu_header:"danhsachcuocu_header.png",
    luat_u_tran:"luat_u_tran.png",
    icon_coinIG:"icon_coin.png",
    icon_coin_hover:"icon_coin_hover.png",
    icon_coin_press:"icon_coin_press.png",
    btn_ga:"btn_ga.png",
    btn_ga_hover:"btn_ga_hover.png",
    btn_ga_press:"btn_ga_press.png",
    btn_ga_disable:"btn_ga_disable.png",
    btn_ga_disable_hover:"btn_ga_disable_hover.png",
    imgTrans68:"imgTrans68.png",
    imgTrans110:"imgTrans110.png",
    avatar_small_bg_bounder_full:"avatar_small_bg_bounder_full.png",
    uMaskCard:"uMaskCard.png",
    btn_xemnoc:"btn_xemnoc.png",
    btn_xemnoc_press:"btn_xemnoc_press.png",
    btn_xemnoc_hover:"btn_xemnoc_hover.png",
    CB:"CB.png",
    chan_1_re:"chan_1_re.png",
    chan_2_re:"chan_2_re.png",
    chan_3_re:"chan_3_re.png",
    chan_4_re:"chan_4_re.png",
    chan_5_re:"chan_5_re.png",
    chan_chia:"chan_chia.png",

    level_0:"level_0.png",
    level_1:"level_1.png",
    level_2:"level_2.png",
    level_3:"level_3.png",
    level_4:"level_4.png",
    level_5:"level_5.png",
    level_6:"level_6.png",
    level_7:"level_7.png",
    level_8:"level_8.png",
    level_9:"level_9.png",
    level_10:"level_10.png",
    level_11:"level_11.png",
    level_12:"level_12.png",

    vv_chat_icon_down:"vv_chat_icon_down.png",
    vv_chat_icon_down_hover:"vv_chat_icon_down_hover.png",
    vv_chat_icon_down_press:"vv_chat_icon_down_press.png",

    vv_chat_icon_up:"vv_chat_icon_up.png",
    vv_chat_icon_up_hover:"vv_chat_icon_up_hover.png",
    vv_chat_icon_up_press:"vv_chat_icon_up_press.png",

    icon_chat_text:"vv_icon_chat_text.png",
    icon_chat_text_hover:"vv_icon_chat_text_hover.png",
    icon_chat_text_press:"vv_icon_chat_text_press.png",
    chat_icon_smile:"vv_chat_icon_smile.png",
    chat_icon_smile_hover:"vv_chat_icon_smile_hover.png",
    chat_icon_smile_press:"vv_chat_icon_smile_press.png",

    vv1_icon_chat_text:"1vv_icon_chat_text.png",
    vv1_icon_chat_text_hover:"1vv_icon_chat_text_hover.png",
    vv1_icon_chat_text_press:"1vv_icon_chat_text_press.png",
    vv1_chat_icon_smile:"1vv_chat_icon_smile.png",
    vv1_chat_icon_smile_hover:"1vv_chat_icon_smile_hover.png",
    vv1_chat_icon_smile_press:"1vv_chat_icon_smile_press.png",

    // vv after login
    dautaydoi_bg: "dautaydoi_bg.png",
    dautaydoi_bg_hover: "dautaydoi_bg_hover.png",
    dinhthuquan_bg: "dinhthuquan_bg.png",
    dinhthuquan_bg_hover: "dinhthuquan_bg_hover.png",
    nhatranh_bg: "nhatranh_bg.png",
    nhatranh_bg_hover: "nhatranh_bg_hover.png",
    footer_bg: "footer_bg.png",
    footer_bg_5_icons: "footer_bg_5_icons.png",
    footer_bg_6_icons: "footer_bg_6_icons.png",
    icon_notification: "icon_notification.png",
    icon_notification_hover: "icon_notification_hover.png",
    icon_tienthuong: "icon_tienthuong.png",
    icon_tienthuong_hover: "icon_tienthuong_hover.png",
    icon_desktop: "icon_desktop.png",
    icon_desktop_hover: "icon_desktop_hover.png",
    icon_cho: "icon_cho.png",
    icon_cho_hover: "icon_cho_hover.png",
    icon_banbe: "icon_banbe.png",
    icon_banbe_hover: "icon_banbe_hover.png",
    icon_hopthu: "icon_hopthu.png",
    icon_hopthu_hover: "icon_hopthu_hover.png",
    btn_napquan_km: "btn_napquan_km.png",

    // vv Setting
    setting_ga_bg: "setting_ga_bg.png",
    edit_password:"edit_password.png",
    ingame_dataydoi_bg_1:"ingame_dataydoi_bg_1.jpg",
    ingame_dataydoi_bg_2:"ingame_dataydoi_bg_2.jpg",
    ingame_dataydoi_bg_3:"ingame_dataydoi_bg_3.jpg",
    ingame_dinhthuquan_bg_1:"ingame_dinhthuquan_bg_1.jpg",
    ingame_dinhthuquan_bg_2:"ingame_dinhthuquan_bg_2.jpg",
    ingame_dinhthuquan_bg_3:"ingame_dinhthuquan_bg_3.jpg",
    ingame_nhatranh_bg_1:"ingame_nhatranh_bg_1.jpg",
    ingame_nhatranh_bg_2:"ingame_nhatranh_bg_2.jpg",
    ingame_nhatranh_bg_3:"ingame_nhatranh_bg_3.jpg",

    // vv top cap thu
    btn_close_circle:"btn_close_circle.png",
    btn_close_circle_hover:"btn_close_circle_hover.png",
    btn_close_circle_press:"btn_close_circle_press.png",
    huanchuong_bg:"huanchuong_bg.png",
    icon_no1:"icon_no1.png",
    icon_no1_2:"icon_no1_2.png",
    icon_no2:"icon_no2.png",
    icon_no3:"icon_no3.png",
    select_tab_content:"select_tab_content.png",
    vv_tct_content_bg:"vv_tct_content_bg.png",
    header_2:"header_2.png",
    img_bnt_dd_dl_1:"img_bnt_dd_dl_1.png",
    img_bnt_dd_dl_2:"img_bnt_dd_dl_2.png",
    img_top_cao_thu_item_hover:"img_top_cao_thu_item_hover.png",
    avatar_out_bg_small:"avatar_out_bg_small.png",
    //VV Seven days bonus
    //daily item sprite
    day_bonus_item_bg_current:"gift_open.png",
    day_bonus_item_bg_past:"gift_disable.png",
    day_bonus_item_bg_past_km:"gift_disable_km.png",
    day_bonus_item_bg_future:"gift_future.png",
    day_bonus_item_gold1:"gold_1.png",
    day_bonus_item_gold2:"gold_2.png",
    day_bonus_item_gold3:"gold_3.png",
    day_bonus_item_gold4:"gold_4.png",
    day_bonus_item_gold5:"gold_5.png",
    day_bonus_item_gold6:"gold_6.png",
    day_bonus_item_btn_nhan_hover:"btn_nhan_hover.png",
    day_bonus_item_btn_nhan_normal:"btn_nhan_normal.png",
    day_bonus_item_btn_nhan_pressed:"btn_nhan_pressed.png",
    day_bonus_item_btn_nhan_disable:"btn_nhan_disable.png",
    day_bonus_item_sticker_KM:"sticker_km.png",
    //seven day bonus windows
    seven_day_bonus_window_bg:"seven_day_bonus_window_bg.png",

    // vv VIP
    arrow_next:"arrow_next.png",
    arrow_previous:"arrow_previous.png",
    bg_money:"bg_money.png",
    btn_vip:"btn_vip.png",
    currentVipBG:"currentVipBG.png",
    icon_explain_hover:"icon_explain_hover.png",
    icon_explain_normal:"icon_explain_normal.png",
    line_vertical:"line_vertical.png",
    listvip_line:"listvip_line.png",
    listvip_viphientai_bottom:"listvip_viphientai_bottom.png",
    listvip_viphientai_top:"listvip_viphientai_top.png",
    nextVipBG:"nextVipBG.png",
    noteBg:"noteBg.png",
    numberbox:"numberbox.png",
    toast_explain:"toast_explain.png",
    vip_btn_deselected:"vip_btn_deselected.png",
    vip_btn_deselected_hover:"vip_btn_deselected_hover.png",
    vip_btn_selected:"vip_btn_selected.png",
    vip_btn_selected_hover:"vip_btn_selected_hover.png",
    vip_icon_help_hover:"vip_icon_help_hover.png",
    vip_icon_help_normal:"vip_icon_help_normal.png",
    vip_image_money:"vip_image_money.png",

    // vv top
    righticon_bg: "righticon_bg.png",
    icon_bxh: "icon_bxh.png",
    icon_bxh_press: "icon_bxh_press.png",
    icon_caidat: "icon_caidat.png",
    icon_caidat_press: "icon_caidat_press.png",
    icon_capture: "icon_capture.png",
    icon_capture_press: "icon_capture_press.png",
    icon_fullscreen: "icon_fullscreen.png",
    icon_fullscreen_press: "icon_fullscreen_press.png",
    icon_fullscreen_close: "icon_fullscreen_close.png",
    icon_fullscreen_close_press: "icon_fullscreen_close_press.png",
    icon_napxu: "btn_napxu.png",
    icon_napxu_hover: "btn_napxu_hover.png",

    icon_roiban: "vv_icon_roiban.png",
    icon_roiban_hover: "vv_icon_roiban_hover.png",
    icon_roiban_press: "vv_icon_roiban_press.png",

    btn_choinhanh: "btn_choinhanh.png",
    btn_choinhanh_hover: "btn_choinhanh_hover.png",

    // vv lobby
    room_name_hover: "room_name_hover.png",
    room_name_press: "room_name_press.png",

    table_hover: "table_hover.png",
    table_no_user: "table_no_user.png",
    table_no_user_dautaydoi: "table_no_user_dautaydoi.png",
    table_no_user_nhatranh: "table_no_user_nhatranh.png",
    hoanhphi_hover: "hoanhphi_hover.png",

    table_ghe_cho: "ghe_cho.png",
    //iconGa:"iconGa.png",
    icon_playing: "icon_playing.png",
    icon_lock: "icon_lock.png",
    icon_coin: "coin.png",
    gagop_roomlist: "gagop_roomlist.png",
    gagop_roomlist_nhatranh: "gagop_roomlist_nhatranh.png",

    // vv avatar
    lobby_avatar_bg: "lobby_avatar_bg.png",
    lobby_avatar_circle: "lobby_avatar_circle.png",
    lobby_avatar_vachchia: "lobby_avatar_vachchia.png",
    level_star_bg: "level_star_bg.png",
    level_star: "level_star.png",
    level_star_no: "level_star_no.png",

    // vv window
    vv_window_header: "vv_window_header.png",
    vv_window_body_bg_1: "vv_window_body_bg_1.png",
    vv_window_body_content: "vv_window_body_content.png",
    vv_btn_close: "vv_btn_close.png",
    vv_btn_close_hover: "vv_btn_close_press.png",

    // vv tab window
    vv_btn_deselected: "btn_deselected.png",
    vv_btn_deselected_hover: "btn_deselected_hover.png",
    vv_btn_selected: "btn_selected.png",
    vv_btn_selected_hover: "btn_selected_hover.png",

    // vv player detail window:
    vv_trangcanhan_avatar_bg: "trangcanhan_avatar_bg.png",
    vv_avatar_out_bg: "avatar_out_bg.png",
    trangthaitaisan: "trangthaitaisan.png",
    tab_congtrang: "tab_congtrang.png",
    tab_thongtincanhan: "tab_thongtincanhan.png",
    thang_thua_bg: "thang_thua_bg.png",
    btn_user_info_edit: "btn_user_info_edit.png",
    btn_user_info_edit_hover: "btn_user_info_edit_hover.png",
    btn_user_info_save: "btn_user_info_save.png",
    btn_user_info_save_hover: "btn_user_info_save_hover.png",
    hc_bachchien_de: "hc_bachchien_de.png",
    hc_thapthanh_de: "hc_thapthanh_de.png",
    hc_uchibachthu_de: "hc_uchibachthu_de.png",
    hc_de: "hc_de.png",
    btn_taisan_avatar: "btn_taisan_avatar.png",
    btn_taisan_avatar_press: "btn_taisan_avatar_press.png",
    btn_taisan_avatar_hover: "btn_taisan_avatar_hover.png",
    btn_taisan_baoboi: "btn_taisan_baoboi.png",
    btn_taisan_baoboi_press: "btn_taisan_baoboi_press.png",
    btn_taisan_baoboi_hover: "btn_taisan_baoboi_hover.png",
    btn_taisan_vatpham: "btn_taisan_vatpham.png",
    btn_taisan_vatpham_press: "btn_taisan_vatpham_press.png",
    btn_taisan_vatpham_hover: "btn_taisan_vatpham_hover.png",
    gach_ngang: "gachngang.png",
    bv_daigia_content_bg: "bv_daigia_content_bg.png",
    trangcanhan_avatar_bg_2: "trangcanhan_avatar_bg_2.png",
    avatar_line:"avatar_line.png",
    icon_laban:"icon_laban.png",
    user_verify:"user_verify.png",

    // vv bonus window
    vv_textInstruction_bg: "textInstruction_bg.png",
    vv_OpenBox: "OpenBox.png",
    vv_CloseBox: "CloseBox.png",
    vv_moiban_facebook: "moiban_facebook_bg.png",
    vv_xacthuc_sdt: "moiban_nguoigioithieunhanthuong_bg.png",
    vv_btn_moiban: "btn_fb.png",
    vv_btn_moiban_hover: "btn_fb_hover.png",
    vv_btn_dongy: "btn_dongy.png",
    vv_btn_dongy_hover: "btn_dongy_hover.png",
    vv_btn_huy: "btn_huy.png",
    vv_btn_huy_hover: "btn_huy_hover.png",
    vv_luckybox_bg: "LuckyBoxbg.png",
    vv_installDesktop: "InstallDesktop.png",

    // vv register phone
    vv_register_phone_step1: "B1.png",
    vv_register_phone_step2: "B2.png",

    // vv shop window
    frame_vatpham_baoboi: "frame_vatpham_baoboi.png",
    vv_tooltip_bg: "sp_cho_hover.png",
    vv_tooltip_arrow: "sp_cho_hover_arrow.png",
    vv_avatar_detail_bg: "avatar_detail_bg.png",

    // vv nap xu window
    napxu_arrow_pos: "arrow_pos.png",
    napxu_arrow_sent: "arrow_sent.png",
    napxu_content_bg: "content_bg.png",
    napxu_edit_text:"napxu_edit_text.png",
    napxu_select:"btn_mang_pressed.png",
    napxu_unselect:"btn_mang_normal.png",
    napxu_store:"naptien_appstore_40.png",
    napxu_note_bg:"note_bg.png",
    napxu_sms_bg: "sms_bg.png",
    napxu_sticker_khuyenmai_big: "sticker_khuyenmai_big.png",
    napxu_board_2columns: "board_2columns.png",
    napxu_board_3columns: "board_3columns.png",
    napxu_banner_red: "banner_red.png",
    napxu_green_dot: "green_dot.png",
    napxu_green_arrow: "green_arrow.png",
    napxu_bubbletalk: "bubbletalk.png",
    image_treasure:"image_treasure.png",
    lightdot:"lightdot.png",
    //vv Post forum Window
    bg_Share_edit_text:"bg_edit_box_share.png",

    // profile update
    bg_profile: "bg_profile.png",
    btn_edit_profile: "btn_edit.png",
    btn_edit_profile_hover: "btn_edit_hover.png",
    btn_save_profile: "btn_save.png",
    btn_save_profile_hover: "btn_save_hover.png",
    // popup hot news
    hotnews_bg: "popup.png",
    hotnews_btn_close_normal: "btn_dong_normal.png",
    hotnews_btn_close_hover: "btn_dong_hover.png",
    hotnews_btn_close_pressed: "btn_dong_pressed.png",
    hotnews_checkbox_normal: "checkbox_normal.png",
    hotnews_checkbox_pressed: "checkbox_pressed.png",
    hotnews_tab_active: "tab_normal.png",
    hotnews_tab_inactive: "tab_pressed.png",

    // login - register
    popup_login_bg: "popup_login.png",
    popup_khoiphucmk: "popup_khoiphucmk.png",
    btnTab_login_active: "tab_login_active.png",
    btnTab_login_inactive: "tab_login_inactive.png",
    iconWarning_login: "icon_warning.png",
    textbox_bg_login: "textbox.png",
    btnLoginNormal: "btn_login_normal.png",
    btnLoginHover: "btn_login_hover.png",
    btnLoginFacebookNormal: "btn_loginfacebook_normal.png",
    btnLoginFacebookHover: "btn_loginfacebook_hover.png",
    checkboxLoginNormal: "login_checkbox_unchecked.png",
    checkboxLoginChecked: "login_checkbox_checked.png",
    hoacSprite: "line_hoac.png",
    bg_chontk:"bg_chontk.png",

    // chess common
    Chess_addplayer: "Chess_addplayer.png",
    Chess_bg_avatar: "Chess_bg_avatar.png",
    Chess_countdown: "Chess_countdown.png",
    Chess_dark_countdown: "Chess_dark_countdown.png",
    ChessRedStatus: "Chess_redstatus.png",
    ActiveAvatar: "active_avatar.png",
    SelectedPiece: "cochonquan.png",
    MovablePiece: "nuocdi.png",
    LastMovePiece: "nuocvuadi.png",
    CanTakenPiece: "trangthai_quananduoc.png",
    ChieuTuongPiece: "trangthai_chieutuong.png",
    BatDauState: "batdau.png",
    HoaState: "hoa.png",
    ChieuTuongState: "chieutuong.png",
    ThongBao: "thongbao.png",
    ThongBaoHover: "thongbao_hover.png",
    ChessToast: "Chess_toast.png",
    BoxQuanAn: "box_quanan.png",
    TimeBoxRed: "time_box_red.png",
    TimeBoxBlack: "time_box_black.png",
    Chess_btn_batdau_normal: "Chess_btn_batdau_normal.png",
    Chess_btn_batdau_pressed: "Chess_btn_batdau_pressed.png",
    Chess_btn_batdau_hover: "Chess_btn_batdau_hover.png",
    Chess_btn_sansang_normal: "Chess_btn_sansang_normal.png",
    Chess_btn_sansang_pressed: "Chess_btn_sansang_pressed.png",
    Chess_btn_sansang_hover: "Chess_btn_sansang_hover.png",
    Chess_btn_tieptuc_normal: "Chess_btn_tieptuc_normal.png",
    Chess_btn_tieptuc_pressed: "Chess_btn_tieptuc_pressed.png",
    Chess_btn_tieptuc_hover: "Chess_btn_tieptuc_hover.png",
    Chess_btn_cauhoa_normal: "Chess_btn_cauhoa_normal.png",
    Chess_btn_cauhoa_pressed: "Chess_btn_cauhoa_pressed.png",
    Chess_btn_cauhoa_hover: "Chess_btn_cauhoa_hover.png",
    Chess_btn_xinthua_normal: "Chess_btn_xinthua_normal.png",
    Chess_btn_xinthua_pressed: "Chess_btn_xinthua_pressed.png",
    Chess_btn_xinthua_hover: "Chess_btn_xinthua_hover.png",
    Chess_btn_cuoctat_normal: "Chess_btn_cuoctat_normal.png",
    Chess_btn_cuoctat_pressed: "Chess_btn_cuoctat_pressed.png",
    Chess_btn_cuoctat_hover: "Chess_btn_cuoctat_hover.png",
    Chess_btn_dunglen_normal: "Chess_btn_dunglen_normal.png",
    Chess_btn_dunglen_pressed: "Chess_btn_dunglen_pressed.png",
    Chess_btn_dunglen_hover: "Chess_btn_dunglen_hover.png",
    Chess_btn_ngoixuong_normal: "Chess_btn_ngoixuong_normal.png",
    Chess_btn_ngoixuong_pressed: "Chess_btn_ngoixuong_pressed.png",
    Chess_btn_ngoixuong_hover: "Chess_btn_ngoixuong_hover.png",

    rb_uncheck:"rb_uncheck.png",
    rb_uncheck_hover:"rb_uncheck_hover.png",
    rb_check:"rb_check.png",
    rb_uncheck_disable:"rb_uncheck_disable.png",
    rb_check_disable:"rb_check_disable.png",

    checkbox_unchecked:"checkbox_unchecked.png",
    checkbox_unchecked_hover:"checkbox_unchecked_hover.png",
    checkbox_checked:"checkbox_checked.png",
    checkbox_unchecked_disable:"checkbox_unchecked_disable.png",
    checkbox_checked_disable:"checkbox_checked_disable.png",

    ImgLeave:"icon_roiban.png",
    ImgLeaveHover:"icon_roiban_hover.png",
    ImgLeave_chess:"icon_roiban_chess.png",
    ImgLeaveHover_chess:"icon_roiban_hover_chess.png",
    ImgNapXu:"btn_napxu.png",
    ImgNapXuHover:"btn_napxu_hover.png",


    ImgTabChooGameNormal:"choseTable_tab_inActive.png",
    ImgTabChooGameSelect:"choseTable_tab_active.png",
    ImgTabChooGameDeSelect:"choseTable_tab_inActive.png",
    ImgTabChooGameDeSelectHover:"choseTable_tab_inActive_hover.png",

    ImgBgAvarAcc:"background_ava_account.png",
    ImgBgAvarAccHover:"background_ava_account_hover.png",
    ImgBgAvarAcc_chess:"background_ava_account_chess.png",
    ImgBgAvarAccHover_chess:"background_ava_account_hover_chess.png",

    Btn_Chat_Text:"icon_chat_text.png",
    Btn_Chat_Text_Hover:"icon_chat_text_hover.png",
    Btn_Chat_Smile:"chat_icon_smile.png",
    Btn_Chat_Smile_Hover:"chat_icon_smile_hover.png",
    Btn_Chat_Down:"chat_icon_down.png",
    Chess_Btn_Chat_Down:"chess_chat_icon_down.png",
    Btn_Chat_Down_Hover:"chat_icon_down_hover.png",
    Btn_Chat_Up:"chat_icon_up.png",
    Chess_Btn_Chat_Up:"chess_chat_icon_up.png",
    Btn_Chat_Up_Hover:"chat_icon_up_hover.png",

    icon_chat_emo_bg_hover:"emo_hover.png",

    btn_scale2:"btn_scale2.png",
    btn_scale2_over:"btn_scale2_over.png",
    btn_scale:"btn_scale.png",
    btn_scale_over:"btn_scale_over.png",
    btn_scale2_chess:"btn_scale2_chess.png",
    btn_scale2_over_chess:"btn_scale2_over_chess.png",
    btn_scale_chess:"btn_scale_chess.png",
    btn_scale_over_chess:"btn_scale_over_chess.png",

    btn_camera:"btn_camera.png",
    btn_camera_over:"btn_camera_over.png",
    btn_camera_chess:"btn_camera_chess.png",
    btn_camera_over_chess:"btn_camera_over_chess.png",
    btn_guide:"btn_guide.png",
    btn_guide_hover:"btn_guide_hover.png",
    btn_guide_chess:"btn_guide_chess.png",
    btn_guide_hover_chess:"btn_guide_hover_chess.png",
    btn_caothu:"btn_caothu.png",
    btn_caothu_over:"btn_caothu_over.png",
    btn_caothu_chess:"btn_caothu_chess.png",
    btn_caothu_over_chess:"btn_caothu_over_chess.png",
    btn_setting:"btn_setting.png",
    btn_setting_over:"btn_setting_over.png",
    btn_setting_chess:"btn_setting_chess.png",
    btn_setting_over_chess:"btn_setting_over_chess.png",

    Lock_IMG:"lock.png",
    Chess_Running_IMG:"chess_running.png",
    Game_Running_IMG:"game_running.png",
    Room_Door_IMG: "room_door_active.png",
    //Room_Hover_IMG:"background_chooseTable_hover.png",
    Room_Hover_IMG:"roomList_bg_hover.png",
    Room_Select_IMG:"roomList_bg_selected.png",
    Room_No_Active_IMG:"room_door_no_active.png",
    chooseTable_line_between_IMG:"chooseTable_line_between_2Room.png",

    //name icon game
    icon_hot: "icon_hot.png",
    icon_new: "icon_new.png",
    icon_3Cay_active:"icon_3Cay_active.png",
    icon_3Cay_hover:"icon_3Cay_hover.png",
    icon_3Cay_waiting:"icon_3Cay_disable.png",
    icon_CoTuong_active:"icon_CoTuong_active.png",
    icon_CoTuong_hover:"icon_CoTuong_hover.png",
    icon_CoTuong_waiting:"icon_CoTuong_disable.png",
    icon_CoUp_active:"icon_CoUp_active.png",
    icon_CoUp_hover:"icon_CoUp_hover.png",
    icon_CoUp_waiting:"icon_CoUp_disable.png",
    icon_Chan_active:"icon_Chan_active.png",
    icon_Chan_hover:"icon_Chan_hover.png",
    icon_Chan_waiting:"icon_Chan_disable.png",
    icon_Lieng_active:"icon_Lieng_active.png",
    icon_Lieng_hover:"icon_Lieng_hover.png",
    icon_Lieng_waiting:"icon_Lieng_disable.png",
    icon_Poker_active:"icon_Poker_active.png",
    icon_Poker_hover:"icon_Poker_hover.png",
    icon_Poker_waiting:"icon_Poker_disable.png",
    icon_Phom_active:"icon_Phom_active.png",
    icon_Phom_hover:"icon_Phom_hover.png",
    icon_Phom_waiting:"icon_Phom_disable.png",
    icon_Sam_active:"icon_Sam_active.png",
    icon_Sam_hover:"icon_Sam_hover.png",
    icon_Sam_waiting:"icon_Sam_disable.png",
    icon_TLMN_active:"icon_TLMN_active.png",
    icon_TLMN_hover:"icon_TLMN_hover.png",
    icon_TLMN_waiting:"icon_TLMN_disable.png",
    icon_TLMNDL_active:"icon_TLMNDL_active.png",
    icon_TLMNDL_hover:"icon_TLMNDL_hover.png",
    icon_TLMNDL_waiting:"icon_TLMNDL_disable.png",
    icon_xiTo_active:"icon_xiTo_active.png",
    icon_xiTo_hover:"icon_xiTo_hover.png",
    icon_xiTo_waiting:"icon_xiTo_disable.png",
    icon_MauBinh_active:"icon_MauBinh_active.png",
    icon_MauBinh_hover:"icon_MauBinh_hover.png",
    icon_MauBinh_waiting:"icon_MauBinh_disable.png",
    icon_Xizach_active:"icon_Xizach_active.png",
    icon_Xizach_hover:"icon_Xizach_hover.png",
    icon_Xizach_waiting:"icon_Xizach_disable.png",
    icon_Xeng_active:"icon_Xeng_active.png",
    icon_Xeng_hover:"icon_Xeng_hover.png",
    icon_Xeng_waiting:"icon_Xeng_disable.png",
    icon_soccer_active:"icon_soccer.png",
    icon_soccer_hover:"icon_soccer_hover.png",

    // button in choose game
    page1:"page1.png",
    page2:"page2.png",

    bookmark_star: "bookmark_star.png",
    btn_bottom_bookmark:"btn_bottom_bookmark.png",
    btn_bottom_bookmark_hover:"btn_bottom_bookmark_hover.png",
    bookmark_title: "bookmark_title.png",
    btn_close_bookmark: "btn_close.png",
    btn_close_bookmark_hover: "btn_close_hover.png",

    btn_close_cuoc: "btn_close_cuoc.png",
    btn_close_cuoc_hover: "btn_close_cuoc_hover.png",

    icon_soccer_back: "icon_soccer_back.png",
    icon_soccer_back_hover: "icon_soccer_back_hover.png",


    btn_bottom_bonus:"btn_bottom_bonus.png",
    btn_bottom_bonus_hover:"btn_bottom_bonus_hover.png",
    btn_bottom_email:"btn_bottom_email.png",
    btn_bottom_email_hover:"btn_bottom_email_hover.png",
    btn_bottom_friend:"btn_bottom_friend.png",
    btn_bottom_friend_hover:"btn_bottom_friend_hover.png",
    btn_bottom_shop:"btn_bottom_shop.png",
    btn_bottom_shop_hover:"btn_bottom_shop_hover.png",
    btn_bottom_task:"btn_bottom_task.png",
    btn_bottom_task_hover:"btn_bottom_task_hover.png",
    btn_bottom_nhanthongbao:"btn_thongbao_normal.png",
    btn_bottom_nhanthongbao_hover:"btn_thongbao_hover.png",
    btn_napTienNew:"btn_napTienNew.png",
    btn_napTienNew_hover:"btn_napTienNew_hover.png",
    icon_addMoney:"icon_addMoney.png",
    icon_addMoney_hover:"icon_addMoney_hover.png",
    bg_addMoney:"bg_addMoney.png",
    bg_addMoney_hover:"bg_addMoney_hover.png",
    bg_addMoney_chess:"bg_addMoney_chess.png",
    bg_addMoney_hover_chess:"bg_addMoney_hover_chess.png",
    btn_next:"btn_next.png",
    btn_prev:"btn_prev.png",
    bg_notification_email:"bg_notification_email.png",
    bg_thongBaoCachDoiTen:"bg_thongBaoCachDoiTen.png",

    // window
    bg_content_shadow : "bg_content_shadow.png",
    BtnClose_Window : "btn_close_popup.png",
    BtnClose_Window_hover : "btn_close_hover_popup.png",
    btnTab_selected : "Tab_active_popup.png",
    btnTab_deselected : "Tab_no_active_popup.png",
    btnTab_deselected_hover: "Tab_no_active_hover_popup.png",
    btn_next_small: "btn_next_small.png",
    btn_back_small: "btn_back_small.png",
    line_big_h: "line_big.png",
    line_medium_h: "line_medium.png",
    bg_avatar_profile: "bg_avatar_profile.png",
    bg_thanhTich:"bg_thanhTich.png",
    bg_KoXepHang:"bg_khongXepHang.png",
    bg_XepHang:"bg_xepHang.png",
    icon_lose:"icon_lose.png",
    //PaymentWd
    viettel_select   : "viettel_select.png",
    mobi_select   : "mobi_select.png",
    vina_select   : "vina_select.png",
    arrow_pos   : "arrow_the_pos.png",
    arrow_pos_payment   : "arrowPosPayment.png",
    board_2columns:"board_2columns.png",
    board_3columns:"board_3columns.png",
    bubbletalk_blue:"bubbletalk_blue.png",
    bubbletalk_orange:"bubbletalk_orange.png",
    icon_mobile:"icon_mobile.png",
    icon_muitenxanh:"icon_muitenxanh.png",
    light_line:"light_line.png",
    gray_line:"grey_line.png",
    textbox_payment:"textbox_payment.png",
    bg_payment:"bg_payment.png",
    editTextPayment:"editTextPayment.png",
    paymentpromotionbg: "paymentpromotionbg.png",

    //Common
    edit_text   : "edit_text.png",
    edit_text_white   : "edit_text_white.png",
    icon_guiMail : "icon_guiMail.png",
    icon_guiMail_hover : "icon_guiMail_hover.png",
    icon_delete : "icon_delete.png",
    icon_delete_hover : "icon_delete_hover.png",
    icon_add_friend:"icon_addFriend.png",
    BtnDialog_Normal : "btn_lightBlue_medium.png",
    BtnDialog_Pressed : "btn_lightBlue_medium_press.png",
    BtnDialog_Inactive : "btn_lightBlue_medium_disable.png",
    BtnDialog_Hover : "btn_lightBlue_medium_hover.png",
    btn_big_normal : "btn_big_normal.png",
    btn_big_press : "btn_big_normal_press.png",
    btn_big_hover : "btn_big_hover.png",
    btn_big_disable : "btn_big_disable.png",
    btn_ready_normal: "btn_sanSang.png",
    btn_ready_press: "btn_sanSang_press.png",
    btn_ready_hover: "btn_sanSang_hover.png",
    btn_small_normal : "btn_small_normal.png",
    btn_small_hover : "btn_small_hover.png",
    icon_sound_off:"icon_sound_off.png",
    icon_sound_on:"icon_sound_on.png",
    MailUnreadIcon: "icon_unread_mail.png",
    MailReadIcon: "icon_read_mail.png",
    MailSentIcon: "icon_sent_mail.png",
    chat_bg_mini:"chat_bg_mini.png",
    chat_bg_mini_co:"chat_bg_mini_co.png",
    card_mask:"mask.png",
    verticalBack:"vertical_back.png",
    arrow:"arrow.png",
    btn_tienCuoc_normal:"btn_tienCuoc.png",
    btn_tienCuoc_Hover:"btn_tienCuoc_hover.png",
    btn_tienCuoc_normal_chess:"btn_tienCuoc_chess.png",
    btn_tienCuoc_Hover_chess:"btn_tienCuoc_hover_chess.png",
    Img_Gold_Box:"luckybox_close.png",
    icon_offline   : "icon_offline.png",
    icon_online   : "icon_online.png",
    ToastBG_png : "toast_background.png",
    vv_toast_background:"vv_toast_background.png",
    busy_indicator : "busy_indicator.png",
    tooltip_bg_arrow: "tooltip_bg_arrow.png",
    tooltip_bg: "tooltip_bg.png",
    btn_googleplay_normal: "btn_download_androi.png",
    btn_googleplay_hover: "btn_download_androi_hover.png",
    btn_appstore_normal: "btn_download_apple.png",
    btn_appstore_hover: "btn_download_apple_hover.png",
    btn_windowsphone_normal: "btn_download_windows.png",
    btn_windowsphone_hover: "btn_download_windows_hover.png",
    btn_dangnhap_normal: "btn_dangNhap.png",
    btn_dangnhap_hover: "btn_dangNhap_hover.png",
    btn_dangky_normal: "btn_dangKy.png",
    btn_dangky_hover: "btn_dangKy_hover.png",
    btn_previous_normal:"btn_prev_FB.png",
    btn_previous_hover:"btn_prev_hover_FB.png",
    btn_previous_press:"btn_prev_press_FB.png",
    btn_previous_disable:"btn_prev_disable_FB.png",

    btn_next_normal:"btn_next_FB.png",
    btn_next_hover:"btn_next_hover_FB.png",
    btn_next_press:"btn_next_press_FB.png",
    btn_next_disable:"btn_next_disable_FB.png",
    check_slected: "check_dachon.png",

    green_frame:"popup_MoiBan_Greenframe.png",
    gray_frame:"popup_MoiBan_Grayframe.png",
    default_Avatar:"default_avatar.jpg",

    //Window base
    Body_Nosub_Window: "window_noSubTab_body_bg.png",
    Header_Nosub_Window: "window_noSbTab_header.png",

    Body_Window: "window_body_bg.png",
    Body_Content_Window: "window_body_content_bg.png",
    Header_Window: "window_header.png",
    Bottom_Window: "window_bottom.png",
    icon_check: "icon_check.png",

    //BonusWd
    luckyBoxbg: "LuckyBoxbg.jpg",
    popup_quaTang: "popup_quaTang.jpg",
    btnPopupQuaTang: "btnPopupQuaTang.png",
    btnPopupQuaTang_hover: "btnPopupQuaTang_hover.png",
    openBox: "OpenBox.png",
    closeBox: "CloseBox.png",
    textInstruction_bg: "bg_tien-thuong.png",
    icon_moiBan: "icon_moiBan.png",
    icon_hopQua: "icon_hopQua.png",
    icon_dangkysdt: "icon_dangkysdt.png",
    icon_desktop: "icon_desktop.png",
    daily_task_open: "daily_task_open.png",
    daily_task_close: "daily_task_close.png",
    icon_daily_task: "icon_daily_task.png",
    //BKPromotionWD
    promotionbg: "promotionbg.png",
    title:"title_nhanthuong.png",
    xacthucTK_sdt_bg: "xacThucTK_bg.png",
    taiapp_Bg:"caidat_bg.png",
    moibanFB_bg:"moiBanFB_bg.png",
    btnNhanXu: "btn_nhanxu.png",
    thuongnapthe_bg:"napThe_bg.png",
    btnNhanXuDisable: "btn_nhanxu_disable.png",
    btnNhanXuPress: "btn_nhanxu_press.png",
    btnNhanXu_hover: "btn_nhanxu_hover.png",
    btnThucHien:"btn_ThucHien.png",
    btnThucHienDisable:"btn_ThucHien_disable.png",
    btnThucHienHover:"btn_ThucHien_hover.png",
    btnThucHienPress:"btn_ThucHien_press.png",
    btnTaiApp:"btn_taingay.png",
    btnTaiAppHover:"btn_taingay_hover.png",
    btnTaiAppPress:"btn_taingay_press.png",
    //Regist Phone
    registerPhoneB1: "btn_buoc1_active.png",
    registerPhoneB2: "btn_buoc2_active.png",
    popup_dangkysdt: "popup_dangkysdt.png",

    //leaderBoard
    popup_leaderboard_bg: "popup_leaderboard_bg.png",
    caothugame_bg:"caothugame_bg.png",
    top_bg_hover:"top_bg_hover.png",
    bg_trandauSprite:"bgTranDauSprite.png",
    bg_trandauSprite_small:"bgTranDauSpritesmall.png",
    popup_top_by_game_bg: "popup_top_by_game_bg.png",
    icon_topDaiGia: "icon_topDaiGia.png",
    icon_topNhietTinh: "icon_topNhietTinh.png",
    tab_top_no_active_hover: "tab_top_no_active_hover.png",
    tab_top_no_active: "tab_top_no_active.png",
    tab_top_active: "tab_top_active.png",
    cao_thu_name_bg: "cao_thu_name_bg.png",
    top_1st_bg: "top_1st_bg.png",
    rank_bg: "rank_bg.png",
    top_10_bg: "top_10_bg.png",
    icon_level: "icon_level.png",
    top_goldcoin: "goldcoin.png",
   top_row_list_hover: "top_row_list_hover.png",

    win: "win.png",
    top_1st: "top_1st.png",
    top_2rd: "top_2rd.png",
    top_3rd: "top_3rd.png",
    btnXet1_IMG:"btn_xet_01.png",
    btnXet1_hover_IMG:"btn_xet_01_hover.png",
    btnXet2_IMG:"btn_xet_02.png",
    btnXet2_hover_IMG:"btn_xet_02_hover.png",
    btnXethet:"btn_xetHet.png",
    btnXethet_press:"btn_xetHet_press.png",
    btnXethet_hover:"btn_xetHet_hover.png",
    EatCard_IMG:"line_outer_poker.png",
    btnGui1_IMG:"send_01.png",
    btnGui1_hover_IMG:"send_01_hover.png",
    btnGui2_IMG:"send_02.png",
    btnGui2_hover_IMG:"send_02_hover.png",
    // round bet game
    bg_bet_button_group: "background_bet_button.png",
    btn_check: "btn_lightBlue_medium.png",
    btn_check_hover: "btn_lightBlue_medium_hover.png",
    btn_check_press: "btn_lightBlue_medium_press.png",
    btn_allIn: "btn_ToTat.png",
    btn_allIn_press: "btn_ToTat_press.png",
    btn_allIn_hover: "btn_ToTat_hover.png",
    bg_lbl_bet_money: "bg_lbl_bet_money.png",
    invisible_btn: "invisible_btn.png",
    bg_suite_name: "bg_suite_name.png",
    bg_suite_name_hover: "bg_suite_name_hover.png",
    bg_suite_detail: "bg_suite_detail.png",
    round_bet_check: "round_bet_check.png",
    round_bet_raise: "round_bet_raise.png",
    round_bet_fold: "round_bet_fold.png",
    round_bet_all_in: "round_bet_all_in.png",
    bet_money_bg0: "bet_money_bg0.png",
    bet_money_bg1: "bet_money_bg1.png",
    card_black_mask: "card_invisible.png",
    result_normal_bg: "result_normal_bg.png",
    slider_dot: "slider_dot.png",
    winner_thungphasanh: "nameGame_ThungPhaSanh.png",
    winner_tuquy: "nameGame_TuQuy.png",
    winner_culu: "nameGame_CuLu.png",
    winner_thung: "nameGame_Thung.png",
    winner_sanh: "nameGame_Sanh.png",
    winner_samco: "nameGame_XamCo.png",
    winner_thu: "nameGame_Thu.png",
    winner_doi: "nameGame_Doi.png",
    winner_mauthau: "nameGame_MauThau.png",
    bet_bg: "bet_bg.png",
    ba_cay_bet_table: "ba_cay_bet_table.png",
    BG_Stop_Watch:"stop_watch.png",
    slider_tract: "slider_track.png",
    slider_ball: "slider_ball.png",
    slider_ball_press: "slider_ball_press.png",
    slider_progress: "slider_progress.png",

    bg_count_down_co:"bg_count_down_co.png",
    avatar_Frame_normal:"avatarFrame.png",
    avatar_Frame_hover:"avatarFrameHover.png",
    bg_VatPham_hover:"bg_vatPham_hover.png",
    autoReadyImg:"text_tuDongSanSang.png",
    bg_userInfo_inGame:"bg_userInfo_inGame.png",
    ingame_AvatarFrame:"bgAva_userInfo_inGame.png",

    xito_bg_r: "xito_bg_r.png",
    xito_bg_l: "xito_bg_l.png",
    info_player: "info_player.png",
    xito_win_bg_border_l:"xito_win_bg_border_l.png",
    xito_win_bg_border_r:"xito_win_bg_border_r.png",
    xito_win_card_border:"xito_win_card_border.png",
    xito_suite_name_bg:"xito_suite_name_bg.png",
    task_bg_item:"bg_task_item.png",

    poker_dealer:"dealer.png",

    arrow_down:"arrow_down.png",
    arrow_up:"arrow_up.png",
    bg_bai_subapp:"bg_bai_subapp.png",
    bg_co_subapp:"bg_co_subapp.png",
    btn_bai_binh_dan:"btn_bai_binh_dan.png",
    btn_bai_solo:"btn_bai_solo.png",
    btn_co_cham:"btn_co_cham.png",
    btn_co_nhanh:"btn_co_nhanh.png",
    btn_bai_binh_dan_hover:"btn_bai_binh_dan_hover.png",
    btn_bai_solo_hover:"btn_bai_solo_hover.png",
    btn_co_cham_hover:"btn_co_cham_hover.png",
    btn_co_nhanh_hover:"btn_co_nhanh_hover.png",
    frame_listgames:"frame_listgames.png",

    thanhSc: "scrollbar_bv_1.png",
    sliderSc: "scrollbar_bv_2_3.png",

    // maubinh
    text_binhlung:"text_binhlung.png",
    text_sap3chi:"text_sap3chi.png",
    bg_sochi:"bg_sochi.png",
    bg_tenchi:"bg_tenchi.png",
    arrow_green:"arrow_green.png",
    arrow_orange:"arrow_orange.png",
    bg_thongbaogiuaban:"bg_thongbaogiuaban.png",

    light_maubinh_big:"light_maubinh_big.png",
    light_maubinh_small:"light_maubinh_small.png",
    light_sochi:"light_sochi.png",

    text_mauthau:"text_mauthau.png",
    text_doi:"text_doi.png",
    text_thu:"text_thu.png",
    text_samco:"text_samco.png",
    text_sanh:"text_sanh.png",
    text_thung:"text_thung.png",
    text_culu:"text_culu.png",

    bacaisanh:"3caisanh.png",
    bacaithung:"3caithung.png",
    sanhrong:"sanhrong.png",
    lucphebon:"lucphebon.png",

    culuchi2:"culuchi2.png",
    samcochicuoi:"samcochicuoi.png",
    tuquy:"tuquy.png",
    thungphasanh:"thungphasanh.png",
    tuquychi2:"tuquychi2.png",
    thungphasanhchi2:"thungphasanhchi2.png",
    AutoWinmaubinh:"maubinh.png",

    blinking:"btn_NhiemVu_haveNewTask.png",
    blinkingPayment:"highlight_naptien.png",
    star:"starlight.png",
    starWhite:"starWhite.png",
    Window_bgMask: "window_bgMask.png",
    viewer:"viewer.png",
    registerExit:"icon_register_exit.png",
    keo_bg:"keobg.png",
    betKeo_bg:"betkeobg.png",
    keo_bgSelected:"keobgSelected.png",

    icon_liveScore:"icon_liveScore.png",
    icon_liveScore_hover:"icon_liveScore_hover.png",

    icon_help_football:"icon_help_football.png",
    icon_help_football_hover:"icon_help_football_hover.png",

    icon_footbalStatistic:"icon_footbalStatistic.png",
    icon_footbalStatistic_hover:"icon_footbalStatistic_hover.png",

};
var res = {
	//Texture Packer
	loginPNG:"res/ImagesVV/loginScene.png",
	loginPlist:"res/ImagesVV/loginScene.plist",
	//ingamePNG:"res/common/ingame.png",
	//ingamePlist:"res/common/ingame.plist",
	//vv_sprite_sheetPNG:"res/vv_sprite_sheet.png",
	//vv_sprite_sheetPlist:"res/vv_sprite_sheet.plist",
	//vv_nap_tien_img:"res/nap_tien.png",
	//vv_nap_tien_plist:"res/nap_tien.plist",
		
		
		// van van res dev
//	    BG_Choosegame:"res/imagesVV_load/background/login_1.jpg",
//	    CHAN_Cards:"res/ImagesVV/bai/bo_chan.png",
//	    resIngameChan_plist: "res/ImagesVV/InGame/Button/resIngame.plist",
//	    resIngameChan_img: "res/ImagesVV/InGame/Button/resIngameImg.png",
//
//	    BG_Lobby_DTQ: "res/imagesVV_load/background/LB_DTQ.jpg",
//	    BG_Lobby_NT: "res/imagesVV_load/background/LB_NT.jpg",
//	    BG_Lobby_Solo: "res/imagesVV_load/background/LB_SOLO.jpg",
//
//	    IG_DTQ_1:"res/imagesVV_load/background/IG_DTQ_1.jpg",
//	    IG_DTQ_2:"res/imagesVV_load/background/IG_DTQ_2.jpg",
//	    IG_DTQ_3:"res/imagesVV_load/background/IG_DTQ_3.jpg",
//	    IG_NT_1:"res/imagesVV_load/background/IG_NT_1.jpg",
//	    IG_NT_2:"res/imagesVV_load/background/IG_NT_2.jpg",
//	    IG_NT_3:"res/imagesVV_load/background/IG_NT_3.jpg",
//	    IG_SOLO_1:"res/imagesVV_load/background/IG_SOLO_1.jpg",
//	    IG_SOLO_2:"res/imagesVV_load/background/IG_SOLO_2.jpg",
//	    IG_SOLO_3:"res/imagesVV_load/background/IG_SOLO_3.jpg",
//
//	    hot_news_img: "res/ImagesVV/hot_news.png",
//	    hot_news_plist: "res/ImagesVV/hot_news.plist",
//
//	    // van van after login
//	    vv_vip_img: "res/ImagesVV/vv_vip.png",
//	    vv_vip_plist: "res/ImagesVV/vv_vip.plist",
//
//	    vv_seven_day_bonus_img:"res/ImagesVV/vv_seven_day_bonus.png",
//	    vv_seven_day_bonus_plist:"res/ImagesVV/vv_seven_day_bonus.plist",

	    vv_after_login_img: "res/ImagesVV/vv_after_login.png",
	    vv_after_login_plist: "res/ImagesVV/vv_after_login.plist",

	    vv_sprite_sheet_img: "res/ImagesVV/vv_sprite_sheet.png",
	    vv_sprite_sheet_plist: "res/ImagesVV/vv_sprite_sheet.plist",
//
//	    vv_bonus_window_img: "res/ImagesVV/vv_bonus_window.png",
//	    vv_bonus_window_plist: "res/ImagesVV/vv_bonus_window.plist",
//
//	    vv_trang_ca_nhan_img: "res/ImagesVV/vv_trang_ca_nhan.png",
//	    vv_trang_ca_nhan_plist: "res/ImagesVV/vv_trang_ca_nhan.plist",
//
//	    vv_shopping_items_img: "res/ImagesVV/vv_shopping_items.png",
//	    vv_shopping_items_plist: "res/ImagesVV/vv_shopping_items.plist",
//
//	    vv_huan_chuong_img: "res/ImagesVV/vv_huan_chuong.png",
//	    vv_huan_chuong_plist: "res/ImagesVV/vv_huan_chuong.plist",
//
	    vv_nap_tien_plist: "res/ImagesVV/nap_tien.plist",
	    vv_nap_tien_img: "res/ImagesVV/nap_tien.png",
//
//	    vv_top_cao_thu_plist: "res/ImagesVV/vv_top_cao_thu.plist",
//	    vv_top_cao_thu_img: "res/ImagesVV/vv_top_cao_thu.png",
//
//	    vv_chucdanh: "res/ImagesVV/Chucdanh/chucdanh.png",
//	    vv_huan_chuong: "res/ImagesVV/HuanChuong/huanchuong.png",
//
//	    vv_avatar_normal:"res/ImagesVV/InGame/avatar_normal.png",
//	    vv_avatar_small:"res/ImagesVV/InGame/avatar_small.png",
//	    avatar_small_bounder:"res/ImagesVV/InGame/avatar_small_bounder.png",
//
//	    // VV Vip
//	    VipBG:"res/ImagesVV/Vip/VipBG.png",
//	    VipBGSmall:"res/ImagesVV/Vip/VipBGSmall.png",
//	    VipBounder:"res/ImagesVV/Vip/VipBounder.png",
//	    VipBounderSmall:"res/ImagesVV/Vip/VipBounderSmall.png",
//
//	    // vv shop items
//	    anhdaidien_in_one: "res/ImagesVV/Shop/HinhAnh/anhdaidien_in_one.png",
//	    avar_code: "res/ImagesVV/Shop/HinhAnh/avar_code.png",
//	    baoboi_code: "res/ImagesVV/Shop/BaoBoi/baoboi.png",
//	    vatpham_code: "res/ImagesVV/Shop/VatPham/vatpham.png",

	    CHAN_GAME_FONT:{type:"font", name:"BRUSHSBI", srcs:["res/fonts/BRUSHSBI.TTF"]},
	    //font
	    GAME_FONT:{type:"font", name:"Roboto", srcs:["res/fonts/Roboto-Regular.ttf"]},
	    GAME_FONT_BOLD:{type:"font", name:"RobotoM", srcs:["res/fonts/Roboto-Medium.ttf"]},

	    //BITMAP_GAME_FONT_BUTTON:"res/fonts/bmfont3.fnt",
//	    BITMAP_GAME_FONT_TCM_THUA:"res/fonts/bmfont2.fnt",
//	    BITMAP_GAME_FONT_TCM:"res/fonts/bmfont1.fnt",
//	    BITMAP_GAME_FONT:"res/fonts/bmfont.fnt",
//	    BITMAP_GAME_FONT_CO:"res/fonts/font.fnt",
//	    BITMAP_GAME_FONT_CHAN:"res/fonts/fontChan.fnt",
//	    snow: "res/common/snow.png",
//	    sakura: "res/common/sakura.png",
//	    hoamai: "res/common/hoamai.png",
//	    flowerbg:"res/common/flowerbg.png",

	    //Player ingame Asset
//	    Player_Asset_img: "res/playerIngameAsset/PlayerIngame.png",
//	    Player_Asset_plist: "res/playerIngameAsset/PlayerIngame.plist",

	    // ingame
//	    // ingame_img: "res/common/ingame.png",
//	    // ingame_plist: "res/common/ingame.plist",
//
//	    vv_chat_emo_static_plist:"res/chat/chatemostatic/chan_emo_chan.plist",
	   // vv_icon_chat_emo_static:"res/chat/chatemostatic/chan_emo_chan.png",

	    // // btn image
	    btn_sprite_sheet_img: "res/ImagesVV/btn_sprite_sheet_img.png",
	    btn_sprite_sheet_plist: "res/ImagesVV/btn_sprite_sheet.plist",




	    //badges
	    // badges_img: "res/badges/badges.png",
	    // badges_plist: "res/badges/badges.plist",
	    //Hot News Wd
	    // hot_news_plist: "res/BonusWindow/hot_news.plist",
	    // hot_news_img: "res/BonusWindow/hot_news.png",
	    //Bonus Wd
	    // tien_thuong_plist: "res/BonusWindow/tien_thuong.plist",
	    // tien_thuong_img: "res/BonusWindow/tien_thuong.png",
	    // shop_item_plist: "res/Shop/shop_item_plist.plist",
	    // shop_item_img: "res/Shop/shop_item_img.png",

	    //Bg_chooTable : "res/bg_chooseTable_scale.jpg",
	    //Bg_Default : "res/DefaultBg.jpg",

//	    Tranperent_IMG: "res/common/null_content.png",
//	    circle_cd:"res/playerIngameAsset/circle.png"
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}
